[package]
name = "void_reckoning_shared"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
uuid = { workspace = true }
